Add safety checks.

diff --git a/server-backup b/server-backup
--- a/server-backup
+++ b/server-backup
@@ -5,84 +5,115 @@
 # Add this script as a cronjob to run daily. It creates an archive of incremental
 # backups, with the current date set as the name of the backup directory.
 # Assumes the script is run from /usr/local/sbin.
+#
+# Date for $DAY0 and $DAY1 is in ISO-8601 format: 
+
 # ------------------------------------------------------------------------------
 # Set directory
-THIS=$(readlink -f ${BASH_SOURCE[0]})
-PROJECT_DIR=$(dirname $THIS)
-
-# Include dependencies
-. "$PROJECT_DIR/variables"
-
-# Todays date in ISO-8601 format:
+THIS=$(readlink -f "${BASH_SOURCE[0]}")
+PROJECT_DIR=$(dirname "${THIS}")
+CONFIG_FILE="${PROJECT_DIR}/server-backup-config"
+SERVERNAME=$(hostname -s)
+HOST=localhost
 DAY0=$(date -I)
-
-# Timestamp
-TIMESTAMP=$(date '+%Y-%m-%d at %H:%M:%S')
-
-# Yesterdays date in ISO-8601 format:
 DAY1=$(date -I -d "1 day ago")
+TIMESTAMP=$(date '+%Y-%m-%d at %H:%M:%S')
+PARENT_DIR="/home/${SERVERNAME}backup"
 
-# The target directory
+# Sanity checks. The main parent directory should exist. If it doesn't, exit early.
+[[ -d "${PARENT_DIR}" ]] || { echo "${PARENT_DIR} doesn't exist or is not a directory. Exiting."; exit 1; }
+
+BACKUP_PATH="${PARENT_DIR}/backup"
+SRC="${PARENT_DIR}/source"
+DB_DUMPS="${SRC}/sql"
 TRG="${BACKUP_PATH}/$DAY0"
-
-# The link destination directory.
 LNK="${BACKUP_PATH}/$DAY1"
 
-# Get list of databases, but not 'Database' or 'information_schema'
-DATABASES=$(mysql --user=$MYSQL_USER --password=$MYSQL_PASSWD -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema)")
+# Include project specific dependencies: required for MySQL credentials
+[[ ! -f "${CONFIG_FILE}" ]] && { echo "Config file missing at ${CONFIG_FILE}"; exit 2; }
+# shellcheck disable=SC1090
+. "$PROJECT_DIR/variables"
 
-# Default for the mysqldump report.
-DUMPFAIL=false
+# Get list of databases, but not 'Database' or 'information_schema'
+get_db_opts=("--user=${MYSQL_USER}" "--password=${MYSQL_PASSWD}" -e "SHOW DATABASES;") 
+DATABASES=$(mysql "${get_db_opts[@]}" | grep -Ev "(Database|information_schema)")
 
 # Remove previously dumped databases from the source directory.
-rm $DB_DUMPS_PATH/*
-
-# Set up log.
-echo "Database backup report. ${TIMESTAMP}" > $DB_DUMPS_PATH/DB_LOG
-echo "=======================================" >> $DB_DUMPS_PATH/DB_LOG
-
-# Create dumps for each database.
-for DB in $DATABASES
-do
-    mysqldump -v --user=$MYSQL_USER --password=$MYSQL_PASSWD --single-transaction --log-error=$DB_DUMPS_PATH/$DB.log --host=$HOST $DB > $DB_DUMPS_PATH/$DB.sql
-    # Log the result of mysqldump.
-    if [[ $? -eq 0 ]]
-    then
-        echo -e "Mysqldump created ${DB}.sql" >> $DB_DUMPS_PATH/DB_LOG
-    else
-        echo "Mysqldump encountered a problem backing up ${DB}. Look in ${DB_DUMPS_PATH}/${DB}.log for information." >> $DB_DUMPS_PATH/DB_LOG
-        $DUMPFAIL=true
-    fi
-done
-
-# The rsync options: follow the symlinks to make a hard backup.
-OPT=(-aqL --progress --exclude='*.zip' --exclude='debian.cnf' --delete --link-dest=$LNK)
-
-# Execute the backup.
-rsync "${OPT[@]}" $SRC/ $TRG
-
-# Log Results.
-if [[ $? -gt 0 ]]
-then
-    # In case of rsync FAILURE.
-    echo "ERROR. rsync didn't complete the nightly backup: ${TIMESTAMP}" >> /var/log/server-backup.log
-    echo "There was an error in the nightly backup for ${SERVERNAME}: ${TIMESTAMP}. See /var/log/server-backup.log."| mail -s "Backup Error, ${SERVERNAME}" ${ADMIN_EMAIL}
-else
-    # In case of rsync SUCCESS.
-    if [[ false == $DUMPFAIL ]]
-
-    # In case of rsync & mysqldump SUCCESS.
-    then
-        echo "SUCCESS. Backup made on: ${TIMESTAMP}" >> /var/log/server-backup.log
-        echo -e "${TIMESTAMP}: Server ${SERVERNAME} successfully ran a local backup.\nBoth rsync & mysqldump report success."| mail -s "Backup Success, ${SERVERNAME}" ${ADMIN_EMAIL}
-
-        # Partial Success: rsync worked but there was at least one mysqldump error
-    else
-        echo "PARTIAL SUCCESS. File backup (rsync) was successful, but mysqldump reports errors: ${TIMESTAMP}" >> /var/log/server-backup.log
-        echo -e "${TIMESTAMP}: Server ${SERVERNAME} ran a local backup.\nFile backup reports success, however mysqldump reports at least one problem.\nCheck "| mail -s "Backup Success, ${SERVERNAME}" ${ADMIN_EMAIL}
-    fi
+if [[ -n "${DB_DUMPS}" ]] && [[ -d "${DB_DUMPS}" ]]; then
+	rm "${DB_DUMPS}"/*.sql
+	rm "${DB_DUMPS}"/*.log
+else 
+	echo "The variable \$DB_DUMPS is not set."
+	exit 3
 fi
 
-# Remove old backups
-cd $BACKUP_PATH
-ls -cpr $BACKUP_PATH | head -n -$RETAIN_NUMBER | xargs -d '\n' rm -rf
+function run_backup {
+	echo "Database backup report. ${TIMESTAMP}" > "${DB_DUMPS}"/db-backup.log
+	echo "==============================================" >> "${DB_DUMPS}"/db-backup.log
+
+	# Default for the mysqldump report.
+	dumpfail=false
+	
+	# We do not use --log-error since this option logs EVERYTHING, not just errors.
+	# If required, consider adding "--log-error=${DB_DUMPS}/${db}".log and 
+	SQL_OPTS=(
+		-v
+		"--user=${MYSQL_USER}"
+		"--password=${MYSQL_PASSWD}"
+		--single-transaction
+		"--host=${HOST}"
+	)
+	# Create dumps for each database.
+	for db in $DATABASES
+	do
+		mysqldump "${SQL_OPTS[@]}" "${db}" > "${DB_DUMPS}/${db}.sql"
+		# shellcheck disable=SC2181
+		if [[ $? -eq 0 ]]
+		then
+			echo -e "Mysqldump created ${DB}.sql" >> "${DB_DUMPS}"/db-backup.log
+		else
+			echo "
+			Mysqldump encountered a problem backing up ${DB}. \
+			" >> "${DB_DUMPS}"/error-mysqldump.log
+			"${dumpfail}"=true
+		fi
+	done
+	# The rsync options: follow the symlinks to make a hard backup.
+	OPT=(-aqL --progress --exclude"="{'*.zip','debian.cnf'} --delete "--link-dest=${LNK}")
+
+	# Execute the backup
+	rsync "${OPT[@]}" "${SRC}"/ "${TRG}"
+	# shellcheck disable=SC2181
+	if [[ $? -gt 0 ]]
+	then
+		# In case of rsync FAILURE.
+		local error_msg="ERROR. rsync on ${SERVERNAME} didn't complete the backup: at ${TIMESTAMP}"
+		echo "${error_msg}" >> /var/log/server-backup.log
+		email_to_admin "${error_msg}" "Backup Error, ${SERVERNAME}" "${ADMIN_EMAIL}"
+	else
+		# In case of rsync SUCCESS.
+		if [[ false == "${dumpfail}" ]]
+		then
+			# rsync & mysqldump SUCCESS.
+			local success_msg="SUCCESS. ${SERVERNAME} backup made on: ${TIMESTAMP}"
+			echo "${success_msg}" >> /var/log/server-backup.log
+			email_to_admin "${success_msg}" "Backup Success, ${SERVERNAME}"
+		else
+			# Partial Success: rsync worked but there was at least one mysqldump error
+			local partial_msg="
+			PARTIAL SUCCESS, backup ${SERVERNAME} on ${TIMESTAMP}. \
+				File backup (rsync) was successful, mysqldump reports errors: ${TIMESTAMP}"
+			echo "${partial_msg}" >> /var/log/server-backup.log
+			email_to_admin "${partial_msg}" "Partial Backup Success, ${SERVERNAME}"
+		fi
+	fi
+
+	# Remove old backups
+	# shellcheck disable=SC2012
+	ls -cprd "${BACKUP_PATH}"/* | head -n -"${RETAIN_NUMBER}" | xargs -d '\n' rm -rf
+
+}
+
+function email_to_admin {
+	echo -e "$1" | mail -s "$2"
+}
diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -3,50 +3,103 @@
 # Set up the incremental backup. Run as sudo.
 # ------------------------------------------------------------------------------
 # Set directory
-THIS=$(readlink -f ${BASH_SOURCE[0]})
-PROJECT_DIR=$(dirname $THIS)
+THIS=$(readlink -f "${BASH_SOURCE[0]}")
+PROJECT_DIR=$(dirname "${THIS}")
+CONFIG_FILE="${PROJECT_DIR}/server-backup-config"
+SERVERNAME=$(hostname -s)
 
-# Include dependencies
-. "$PROJECT_DIR/variables"
+# Include project specific dependencies
+[[ ! -f "${CONFIG_FILE}" ]] && { echo "Config file missing at ${CONFIG_FILE}"; exit 1; }
+# shellcheck disable=SC1090
+. "${CONFIG_FILE}"
 
-function setup() {
-    # Make the Backup directory
-    mkdir -p ${BACKUP_PATH}
+BACKUP_USERNAME="${SERVERNAME}backup"
 
-    # Make the source directory
-    mkdir -p ${SRC}
+# The source directory: this should contain a symlink to Apache doc root.
+PARENT_DIR="/home/${BACKUP_USERNAME}"
 
-    # Make the config directory if it does not exist.
-    mkdir -p ${CONFIG}
+# The Directory that holds backups
+BACKUP_PATH="${PARENT_DIR}/backup"
 
-    # Make the target for mysqldump
-    mkdir -p ${DB_DUMPS_PATH}
+# Directory for the source files: to be backed up
+SRC="${PARENT_DIR}/source"
 
-    # Add a symlink to site files into the source directory.
-    ln -s /var/www/html ${SRC}
+# The directory that holds dumped databases.
+DB_DUMPS_PATH="${SRC}/sql"
 
-    # Symlink Apache config files into source/config (including vhosts setup)
-    ln -s /etc/apache2 ${CONFIG}
+# The directory holding source config files
+CONFIG="${SRC}/config"
 
-    # Symlink MySQL config files
-    ln -s /etc/mysql ${CONFIG}
+function create_backup_user {
+	[[ $(getent passwd "${BACKUP_USERNAME}") ]] && { echo "${BACKUP_USERNAME} exists."; return 0; }
 
-    # Make the backup script executable
-    chmod +x $PROJECT_DIR/server-backup
-
-    # Symlink MySQL config files
-    ln -s $PROJECT_DIR/server-backup /usr/local/sbin
+	local match=0
+	local new_pass=
+	local conf=
+	while [ "${match}" -eq "0" ]; do
+		read -srp "Enter new UNIX password: " new_pass
+		printf "\n"
+		read -srp "Retype new UNIX password: " conf
+		printf "\n"
+		if [[ "${new_pass}" != "${conf}" ]]; then
+			echo "Passwords do not match. Try again."
+		else
+			match=1
+		fi
+	done
+	adduser --disabled-password "${BACKUP_USERNAME}"
+	echo "${BACKUP_USERNAME}:${new_pass}" | chpasswd
+	usermod -aG sudo "${BACKUP_USERNAME}"
 }
 
-echo ""
-echo "This script sets up backup directories and necessary symlinks."
-echo "You only need to run this script ONCE. It's probably a good idea to read the readme!"
-echo "Before running, server specific variables must be set in ${PROJECT_DIR}/variables."
-echo "If you haven't done this, stop and do so before continuing."
-echo ""
-read -p "Do you want to continue (y/n)?" CONT
-if [ "$CONT" = "y" ]; then
-    setup;
-else
-    echo "Cancelled.";
-fi
+function create_mysql_backup_user {
+	sudo mysql -u root -e "
+	CREATE USER '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASSWD}';
+	GRANT SELECT, SHOW VIEW, RELOAD, REPLICATION CLIENT, EVENT, TRIGGER ON *.* TO '${MYSQL_USER}'@'localhost';
+	FLUSH PRIVILEGES;
+	SHOW GRANTS FOR '${MYSQL_USER}'@localhost';
+	"
+}
+
+function setup_dirs {
+	# Make the Backup directory
+	mkdir -p "${BACKUP_PATH}"
+
+	# Make the source directory
+	mkdir -p "${SRC}"
+
+	# Make the config directory if it does not exist.
+	mkdir -p "${CONFIG}"
+
+	# Make the target for mysqldump
+	mkdir -p "${DB_DUMPS_PATH}"
+
+	# Add a symlink to site files into the source directory.
+	ln -s /var/www/html "${SRC}"
+
+	# Symlink Apache config files into source/config (including vhosts setup)
+	ln -s /etc/apache2 "${CONFIG}"
+
+	# Symlink MySQL config files
+	ln -s /etc/mysql "${CONFIG}"
+
+	# Make the backup script executable
+	chmod +x "${PROJECT_DIR}"/server-backup
+
+	# Symlink MySQL config files
+	ln -s "${PROJECT_DIR}"/server-backup /usr/local/sbin
+}
+
+echo "
+This script sets up backup directories and necessary symlinks.
+You only need to run this script ONCE. It's probably a good idea to read the readme!
+Before running, server specific variables must be set in ${PROJECT_DIR}/variables.
+If you haven't done this, stop and do so before continuing.
+"
+
+read -rp "Do you want to proceed? [y/N]?" choice
+[[ ! "${choice}" =~ ^(yes|YES|y|Y)$ ]] && { echo "Exiting."; exit 1; }
+
+create_backup_user
+create_mysql_backup_user
+setup_dirs
